[package]
name = "fledge-os"
version = "0.1.0"
authors = ["penkwe"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.7"
x86_64 = "0.14"

[package.metadata.bootimage]
default-target = "fledge.json"
